# Generated by Django 4.2.1 on 2023-07-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Phone_no',
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_no',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
